from core.webviews.products_views import (
    CategoryDeleteView,
    CategoryListCreateView,
    CategoryUpdateView,
    ProductCreateView,
    ProductDeleteView,
    ProductInfoView,
    ProductListView,
    ProductStockAdjustView,
    ProductSheetFieldDeleteView,
    ProductSheetFieldListCreateView,
    ProductSheetUrlCreateView,
    ProductSheetUrlDeleteView,
    ProductUpdateView,
    SupplierDeleteView,
    SupplierListCreateView,
)

__all__ = [
    'CategoryDeleteView',
    'CategoryListCreateView',
    'CategoryUpdateView',
    'ProductCreateView',
    'ProductDeleteView',
    'ProductInfoView',
    'ProductListView',
    'ProductStockAdjustView',
    'ProductSheetFieldDeleteView',
    'ProductSheetFieldListCreateView',
    'ProductSheetUrlCreateView',
    'ProductSheetUrlDeleteView',
    'ProductUpdateView',
    'SupplierDeleteView',
    'SupplierListCreateView',
]
