# Generated by Django 6.0.2 on 2026-04-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_eventcomment_is_ignored_by_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='app_time_zone',
            field=models.CharField(default='UTC', max_length=64),
        ),
    ]
