# Generated by Django 6.0.2 on 2026-04-13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_systemsettings_app_time_zone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemTestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('io_rw', 'Read/write test'), ('db', 'Database test'), ('requirements', 'System requirements test'), ('data_quality', 'Data quality test')], max_length=32)),
                ('supported', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('fail', 'Fail'), ('skipped', 'Skipped')], max_length=16)),
                ('duration_ms', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_test_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['test_type', 'created_at'], name='core_system_test_type_d29ad4_idx')],
            },
        ),
    ]
