# Generated by Django 6.0.2 on 2026-04-13 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_asset_assetimage_assetreservation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='allow_negative_balance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='refund_hours_threshold',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='assetreservation',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_asset_reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetreservation',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetreservation',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='assetreservation',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='assetreservation',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetreservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='pricing_mode',
            field=models.CharField(choices=[('free', 'Free'), ('total', 'Total price'), ('hourly', 'Price per hour')], default='total', max_length=20),
        ),
    ]
