# Generated by Django 6.0.2 on 2026-04-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_asset_allow_negative_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
