"""
Django settings for CashFlow project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path
from urllib.parse import parse_qs, unquote, urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


def _env_list(name, default=''):
    raw_value = os.getenv(name, default)
    return [item.strip() for item in raw_value.split(',') if item.strip()]


def _build_database_config():
    database_url = (os.getenv('DATABASE_URL') or '').strip()
    conn_max_age = int(os.getenv('DB_CONN_MAX_AGE', '60'))

    if database_url:
        parsed = urlparse(database_url)
        scheme = (parsed.scheme or '').lower()

        if scheme in {'postgres', 'postgresql', 'psql'}:
            query = parse_qs(parsed.query)
            options = {}
            if query.get('sslmode'):
                options['sslmode'] = query['sslmode'][0]
            return {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': unquote((parsed.path or '/').lstrip('/')),
                'USER': unquote(parsed.username or ''),
                'PASSWORD': unquote(parsed.password or ''),
                'HOST': parsed.hostname or '127.0.0.1',
                'PORT': str(parsed.port or '5432'),
                'CONN_MAX_AGE': conn_max_age,
                'OPTIONS': options,
            }

        if scheme == 'sqlite':
            sqlite_path = unquote(parsed.path or '').strip() or str(BASE_DIR / 'db.sqlite3')
            return {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': sqlite_path,
            }

    engine = os.getenv('DB_ENGINE', 'django.db.backends.sqlite3').strip()
    if engine == 'django.db.backends.sqlite3':
        return {
            'ENGINE': engine,
            'NAME': os.getenv('DB_NAME', str(BASE_DIR / 'db.sqlite3')).strip(),
        }

    db_options = {}
    db_sslmode = (os.getenv('DB_SSLMODE') or '').strip()
    if db_sslmode:
        db_options['sslmode'] = db_sslmode

    return {
        'ENGINE': engine,
        'NAME': os.getenv('DB_NAME', '').strip(),
        'USER': os.getenv('DB_USER', '').strip(),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', '127.0.0.1').strip(),
        'PORT': os.getenv('DB_PORT', '').strip(),
        'CONN_MAX_AGE': conn_max_age,
        'OPTIONS': db_options,
    }


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'SECRET_KEY',
    'fN4x7#tqP9!bL2@uR8$kM3^wY6&hC1*zD5%jV0+sA4=Qe7!pL9',
)

# SECURITY WARNING: don't run with debug turned on in production!
IS_TESTING = 'test' in sys.argv
IS_RUNSERVER = 'runserver' in sys.argv
debug_env = os.getenv('DEBUG')
if debug_env is None:
    # Enable DEBUG by default for local runserver only.
    DEBUG = IS_RUNSERVER
else:
    DEBUG = _env_bool('DEBUG', default=False)

ALLOWED_HOSTS = _env_list(
    'ALLOWED_HOSTS',
    'cashflow,cashflow.local,127.0.0.1,192.168.1.129',
)
CSRF_TRUSTED_ORIGINS = _env_list(
    'CSRF_TRUSTED_ORIGINS',
    'http://127.0.0.1,http://localhost',
)


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'rest_framework',
    'core',
    'inventory',
    'sales',
    'customers',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.UserSessionActivityMiddleware',
    'core.middleware.UserLanguageMiddleware',
    'core.middleware.BackendSecurityLoggingMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'CashFlow.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.admin_pending_counts',
                'core.context_processors.current_user_profile',
                'core.context_processors.ui_settings',
            ],
            'builtins': [
                'core.templatetags.core_numbers',
            ],
        },
    },
]

WSGI_APPLICATION = 'CashFlow.wsgi.application'
ASGI_APPLICATION = 'CashFlow.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': _build_database_config(),
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('en', 'English'),
    ('es', 'Español'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

BACKEND_LOG_FILE = BASE_DIR / 'backendlog.log'
BACKEND_LOG_RETENTION_DAYS = int(os.getenv('BACKEND_LOG_RETENTION_DAYS', '3'))

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
}

SECURE_SSL_REDIRECT = _env_bool('SECURE_SSL_REDIRECT', default=True) and not DEBUG and not IS_TESTING and not IS_RUNSERVER
SESSION_COOKIE_SECURE = _env_bool('SESSION_COOKIE_SECURE', default=True) and not IS_TESTING and not IS_RUNSERVER
CSRF_COOKIE_SECURE = _env_bool('CSRF_COOKIE_SECURE', default=True) and not IS_TESTING and not IS_RUNSERVER
SECURE_HSTS_SECONDS = 0 if IS_RUNSERVER else int(os.getenv('SECURE_HSTS_SECONDS', '31536000'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=True)
SECURE_HSTS_PRELOAD = _env_bool('SECURE_HSTS_PRELOAD', default=True)
USE_X_FORWARDED_HOST = _env_bool('USE_X_FORWARDED_HOST', default=True)
USE_X_FORWARDED_PORT = _env_bool('USE_X_FORWARDED_PORT', default=True)

if _env_bool('USE_X_FORWARDED_PROTO', default=True):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'
X_FRAME_OPTIONS = 'DENY'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[%(asctime)s] %(levelname)s %(name)s: %(message)s',
        },
        'simple': {
            'format': '%(levelname)s %(name)s: %(message)s',
        },
    },
    'handlers': {
        'backendlog_file': {
            'level': 'INFO',
            '()': 'core.logging_handlers.WindowsSafeTimedRotatingFileHandler',
            'filename': BACKEND_LOG_FILE,
            'when': 'midnight',
            'interval': 1,
            'backupCount': BACKEND_LOG_RETENTION_DAYS,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        'console': {
            'class': 'logging.StreamHandler',
            'level': 'WARNING',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'backendlog': {
            'handlers': ['backendlog_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.server': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'daphne.server': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'daphne.ws_protocol': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'channels': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
