# Generated by Django 6.0.2 on 2026-03-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_product_purchase_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='min_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
