# Generated by Django 6.0.2 on 2026-02-24 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeuserprofile',
            options={'verbose_name': 'Store profile', 'verbose_name_plural': 'Store profiles'},
        ),
    ]
