# Generated by Django 6.0.2 on 2026-02-25 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_balancelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeuserprofile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Español')], default='en', max_length=5),
        ),
    ]
