# Generated by Django 6.0.2 on 2026-02-26 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_storeuserprofile_profile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storeuserprofile',
            name='monthly_fee_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storeuserprofile',
            name='monthly_fee_enabled_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeuserprofile',
            name='monthly_fee_last_charged_month',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='balancelog',
            name='source',
            field=models.CharField(choices=[('manual_adjustment', 'Manual adjustment'), ('balance_request_approval', 'Balance request approval'), ('order_approval', 'Order approval'), ('monthly_fee', 'Monthly fee charge')], max_length=50),
        ),
        migrations.CreateModel(
            name='MonthlyFeeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_monthly_fee_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly fee settings',
                'verbose_name_plural': 'Monthly fee settings',
            },
        ),
    ]
