# Generated by Django 6.0.2 on 2026-03-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_storeuserprofile_show_all_recent_movements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeuserprofile',
            name='password_change_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='balancelog',
            name='source',
            field=models.CharField(choices=[('manual_adjustment', 'Manual adjustment'), ('balance_request_approval', 'Balance request approval'), ('order_approval', 'Order approval'), ('monthly_fee', 'Monthly fee charge'), ('event_registration_charge', 'Event registration charge'), ('event_registration_refund', 'Event registration refund')], max_length=50),
        ),
    ]
