# Generated by Django 6.0.2 on 2026-02-24 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleitem',
            options={'verbose_name': 'Sale item', 'verbose_name_plural': 'Sale items'},
        ),
    ]
