# Generated by Django 6.0.2 on 2026-03-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_soft_delete_sale_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
